### ISSUE TITLE
Deep immutable patching?

### ISSUE THREAD

**Issue by pygy** [barneycarroll/patchinko#3]
```JS
// patchinko/immutable.js

ptk = require('.')

function ipatch(...attrs) {
  return ptk.patch({}, ...attrs)
}

function ips(input){
  return new scope(function(definition){
    return ipatch(definition, input)
  })
}

try {
  module.exports = {patch: ipatch, scope: ptk.scope, ps: ips}
} catch(e) {}

```
PR? (with ipatch compiled to ES5, off course)

**Comment by leeoniya** [comment]
@pygy https://github.com/barneycarroll/patchinko/issues/2

**Comment by pygy** [comment]
Freezer is small (~3.5k mingzipped) and handles many more scenarios, but just having this combined with streams would go a long way for me (`patchinko/index.js` is 308 bytes gzipped, as served by unpkg).

**Comment by barneycarroll** [comment]
I'm struggling to understand the value proposition here. Surely immutability is the incidental lack of mutation, which can always be achieved by the provision of a new object and the discarding of the old?

**Comment by leeoniya** [comment]
> I'm struggling to understand the value proposition here.

freezer, though, will mutate the entire branch, allowing for cheap diffing / sCU: https://github.com/arqex/freezer#why-another-state-holder

**Comment by pygy** [comment]
Time travel/snapshots, ... without deep cloning. That's how assocPath is implemented in Ramda for example.

`ps` mutates the child object.

[https://flems.io/#0=N4Ig9grgLgDtIC4oCcIFMA0IDOaA2aAxlGgCaIgB0AVtiFgGYCWBdCA2qAHYCGAtmgqUAFlD556IQmC4lZFEAF8M3foIRVak6bLTyNDCF2JMZAAiYweUQsIAUlR9ZTYAlGeAAdLmbPI0UBDIPlY29sDKZo6Uzshu3ore3obGUKY+lth2TFxwUK5ePn4BQT5caADuZtjSMGh2KSYydqRozFxMaTIF3r6+-oHBFqG2LW05nekYFrnQrr1mivNciVzeOthQZjxmALweAEYIHoQIAGyRpMcRq+sym9sATHtmI-Y808BHr1nAp2YAdiWSySxnuYAIlDwYAA5nZgDwQWCuNgIWgobD4TxHki7ii0Ri4QByAC0ZPJFIpROWeIeTB2+y+11OF2mVw8iluyLp2Jelmso3pn2+mXh-yBrlx3IJ0LhwHpSI2Msx8uxivBkNl2R4lFIe12+3pj11riUKhAvAEQkI2DoWB0cigCkUAF0sHgcgBrNicEBBCQaUSwbAIAD0oaMME9MMo0j4obeXrAAAEAIyUdMABlDOVaAA8aHaQFAAJ51ChaV2KIA](flems here)

**Comment by pygy** [comment]
You'd have to check for arrays as well (ipatch would turn them into objects)

**Comment by barneycarroll** [comment]
`patch` can accept a fresh entity as first argument, `scope` will return whatever you want it to… Is `ps` the only thing that requires rethinking in order to provide a proper 'fresh outcomes' functional suite?

@leeoniya do you think this lib can or should be modified to meet some of the aims of Freezer?

**Comment by leeoniya** [comment]
i mentioned Freezer to hopefully save you guys from reinventing it.

Freezer feels like a very focused lib with a small api. i suspect any significant size reduction would come at the cost of handling corner cases, perf, browser compat, or something else. tbh, there's a lot more value in branch-immutability than in byte size when we're talking a difference of 2.5k. patchinko needs to offer some benefit that's more than skin-deep, something that's awkward to do in Freezer. right now, i'm struggling to find what that is.

there's almost certainly higher perf and lower mem usage in mutable structures. the question is, how much better is it? keeping in mind that a data store is rarely the bottleneck in client code, it's always dom mutation and i/o.

**Comment by pygy** [comment]
@barneycarroll correct

`ps` could be amended to accept a replacement object (or not at all and leave more advanced versions as an exercise for the ~~reader~~ user).

**Comment by pygy** [comment]
@leeoniya `patchinko` is also a monkey patching helper (since it can patch in place), something that Freezer can't do at all AFAICT.

**Comment by barneycarroll** [comment]
PR welcome @pygy!

**Comment by leeoniya** [comment]
> do you think this lib can or should be modified to meet some of the aims of Freezer?

i guess my short answer would be "no" :) shallow immutability is of limited use and freezer does deep immutability very well. i don't see much value in having a lib that handles both with various limitations and caveats, since the patterns are conceptually opposites and mixing them in an app would be rather odd.

**Comment by pygy** [comment]
We're good as far as I'm concerned

**Comment by barneycarroll** [comment]
Closing this to draw a line under the Freezer comparison & re-opening to consider what else needs doing for Patchinko to be able to address immutable workflows in its own way in light of #4. 

It took me a while to understand how such a small patch could address the problem so comprehensively, which is a sure sign that the documentation needs re-working!

The more involved concerns of patching are broadly speaking incompatible with those of immutable workflows — monkey patching a stateful prototypal entity in subtle ways in order to modify its behaviour when invoked elsewhere is one thing, making a deep copy of a structure with modifications here and there, preserving the original reference and creating a new one… are concerns coming from different places, and the vagaries of Javascript mean that there is no procedural middle ground (a perfect copy of any given Javascript object is an ambiguous instruction).

The documentation needs expanding and I think the kitchen sink example no longer works given this new feature. 

Is it sufficient to say that `patch(new a.constructor, a, {...patchA, ps(new b.constructor, patchB)})` as a pattern addresses the generic concern of immutable Patchinko?

**Comment by pygy** [comment]
> It took me a while to understand how such a small patch could address the problem

I got the insight from your comment above: "Is ps the only thing that requires rethinking in order to provide a proper 'fresh outcomes' functional suite?". And yes, it was :-)

> Is it sufficient to say that `patch(new a.constructor, a, {...patchA, ps(new b.constructor, patchB)})` as a pattern addresses the generic concern of immutable Patchinko?

That and a similar note for `ps()`, but otherwise, I'd say yes.

**Comment by barneycarroll** [comment]
🎉
